// Renders Mark's icon set from the artwork in brand/: the app icon at every
// size and the .icns, the menu bar glyph, and src/mark.ts for the editor's
// empty state. Run from the project root:  node scripts/build-icon.mjs
import { chromium } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync, copyFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const artwork = path.join(root, 'brand/mark-dark.svg');
const icons = path.join(root, 'src-tauri/icons');
const work = path.join(root, 'src-tauri/target/icon-build');
const svg = readFileSync(artwork, 'utf8');
rmSync(work, { recursive: true, force: true }); mkdirSync(path.join(work, 'Mark.iconset'), { recursive: true });

// ---- the parts of the artwork the app draws itself ---------------------------------
/** The arrow is the first path under the arrow's shadow filter; the corners are
 *  the stroked path before it. Both are taken verbatim, so the empty state and
 *  the menu bar cannot drift from the icon. */
const arrow = svg.match(/<g filter="url\(#arrow-shadow\)">\s*<path d="([^"]+)"/)?.[1];
const corners = svg.match(/<path d="([^"]+)" fill="none" stroke="url\(#corner\)"/)?.[1];
if (!arrow || !corners) throw new Error('brand/mark-dark.svg has changed shape; update the two matches above.');
writeFileSync(path.join(root, 'src/mark.ts'), `// Generated by scripts/build-icon.mjs from brand/mark-dark.svg. Do not edit by hand.

/** The arrow of Mark's icon, as a path in the icon's 1024-unit square. */
export const MARK_ARROW = '${arrow}';
/** The two capture corners it points between. */
export const MARK_CORNERS = '${corners}';
`);

// ---- the menu bar glyph -----------------------------------------------------------------
/** Alpha only, so macOS tints it for light, dark and highlighted menu bars; the
 *  arrow alone, scaled to fill the canvas, since the corners are clutter at 22
 *  points. The bounds come from the path's own numbers. */
const numbers = arrow.match(/-?\d+(?:\.\d+)?/g).map(Number);
const xs = numbers.filter((_, i) => i % 2 === 0), ys = numbers.filter((_, i) => i % 2 === 1);
const box = { x: Math.min(...xs), y: Math.min(...ys), w: Math.max(...xs) - Math.min(...xs), h: Math.max(...ys) - Math.min(...ys) };
const fit = 900 / Math.max(box.w, box.h);
const tray = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="44" height="44">
  <path d="${arrow}" fill="#000000" transform="translate(512 512) scale(${fit.toFixed(4)}) translate(${(-(box.x + box.w / 2)).toFixed(1)} ${(-(box.y + box.h / 2)).toFixed(1)})"/>
</svg>`;
writeFileSync(path.join(work, 'tray.svg'), tray);

// ---- the icon at every size ---------------------------------------------------------------
/** One artwork, rendered per size: the file's own width and height are swapped
 *  for the target's, so the browser rasterises the vectors at that size rather
 *  than scaling a bitmap. */
const sizes = [16, 32, 64, 128, 256, 512, 1024];
for (const px of sizes) {
  writeFileSync(path.join(work, `icon-${px}.svg`), svg.replace(/width="1024" height="1024"/, `width="${px}" height="${px}"`));
}
const browser = await chromium.launch();
async function render(file, px, target) {
  const page = await browser.newPage({ viewport: { width: px, height: px }, deviceScaleFactor: 1 });
  await page.goto('file://' + file);
  await page.screenshot({ path: target, omitBackground: true });
  await page.close();
}
for (const px of sizes) await render(path.join(work, `icon-${px}.svg`), px, path.join(work, `icon-${px}.png`));
await render(path.join(work, 'tray.svg'), 44, path.join(icons, 'tray.png'));
await browser.close();

// What tauri.conf.json names, and what macOS's iconset wants.
const named = { '32x32.png': 32, '64x64.png': 64, '128x128.png': 128, '128x128@2x.png': 256, 'icon.png': 1024 };
for (const [name, px] of Object.entries(named)) copyFileSync(path.join(work, `icon-${px}.png`), path.join(icons, name));
const iconset = { 16: ['icon_16x16.png'], 32: ['icon_16x16@2x.png', 'icon_32x32.png'], 64: ['icon_32x32@2x.png'],
  128: ['icon_128x128.png'], 256: ['icon_128x128@2x.png', 'icon_256x256.png'], 512: ['icon_256x256@2x.png', 'icon_512x512.png'], 1024: ['icon_512x512@2x.png'] };
for (const [px, names] of Object.entries(iconset)) for (const name of names) copyFileSync(path.join(work, `icon-${px}.png`), path.join(work, 'Mark.iconset', name));
execFileSync('iconutil', ['--convert', 'icns', '--output', path.join(icons, 'icon.icns'), path.join(work, 'Mark.iconset')]);
console.log(`icons: ${Object.keys(named).join(', ')}, icon.icns, tray.png; and src/mark.ts`);
